In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [30]:
df=pd.read_csv("MultiVariHomePrice.csv")
df

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [31]:
import math
median_Bedroom = math.floor(df.Bedroom.median())
median_Bedroom

3

In [46]:
df.Bedroom=df.Bedroom.fillna(median_Bedroom)
df

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [47]:
reg=linear_model.LinearRegression()
reg.fit(df[['Area','Bedroom','Age']],df.Price)

LinearRegression()

In [48]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [49]:
reg.intercept_

383724.99999999994

In [51]:
reg.predict([[3000,3,40]])

array([444400.])

In [40]:
118.40231951*3000 + -4718.06464295*15 +313509.1685153465

597945.1574010965

In [52]:
reg.predict([[2500,4,5]])

array([588625.])